#!/bin/bash
aseqdump -p "Impact LX49+" | \
while IFS=" ," read src ev1 ev2 ch label1 data1 label2 data2 rest; do
    case "$ev1 $ev2 $data1" in
        "Control change 66" ) xdotool key Down ;;
        "Control change 67" ) xdotool key Up ;;
    esac
done
